articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'


urlpatterns = [
    path('index/', views.index, name='index'),
    # variable routing
    path('<int:article_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # variable routing
    path('edit/<int:article_pk>/', views.edit, name='edit'),
    path('update/<int:article_pk>/', views.update, name='update'),
    # variable routing
    path('delete/<int:article_pk>/', views.delete, name='delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    
    # 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)
    # 수정 시간
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목 : {self.title}'

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    # ORM
    # class.manager.query API
    # 함수의 실행 결과를 변수에 담는다.
    articles = Article.objects.all()
    context = {
        # 특정 단어 혹은 알파벳을 영역 선택후
        # ctrl + d 하면 같은 단어 다 찾아줌
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_pk):
    # 특정 게시글 하나 조회
    # class.manager.query API
    # 함수 실행 -> article_pk와 pk값이 동일한 게시글 하나 조회
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # 게시글 생성 요청에 대한 응답
    # 게시글을 생성만 해주면 되는게 이 view 함수의 일이다.
    # 진짜 게시글만 만들어주면 UX가 박살남.
    # 게시글 생성 후에, 특정 페이지를 사용자에게 반환 할 수 있도록
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    

    # 다른 요청 경로로 이동시킨다.
    return redirect('articles:detail', article.pk)

def edit(request, article_pk):
    # class.manage.query API
    article = Article.objects.get(pk=article_pk)
    context = {
        'article':article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article_pk)


def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL PAGE</h1>
  <p>제목 {{ article.title }}</p>
  <p>내용 {{ article.content }}</p>
  <p>작성 {{ article.created_at }}</p>
  <p>수정 {{ article.updated_at }}</p>

  <a href="{% url 'articles:edit' article.pk %}">[EDIT]</a>
  <form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value="DELETE">

  </form>
{% endblock content %}

articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>EDIT PAGE</h1>
  <form action="{% url 'articles:update' article.pk %}" method='POST'>
    {% csrf_token %}
    {% comment %} 제목 {% endcomment %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title" value="{{ article.title }}">
    <br>

    {% comment %} 내용 {% endcomment %}
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}
    </textarea>
    {% comment %} 제출버튼 {% endcomment %}
    <input type="submit" value="게시글 수정">
  </form>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>
  <a href="{% url 'articles:new' %}">
    [NEW]
  </a>
    {% for article in articles %}
      <p>{{ article.pk }}번 게시글</p>
      {% comment %}
        {% url 'app_name:url_name' %}
      {% endcomment %}
      <a href="{% url 'articles:detail' article.pk %}">
        <p>제목 : {{ article.title }}</p>
      </a>
      <hr>
    {% endfor %}
{% endblock content %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW PAGE</h1>
  <form action="{% url 'articles:create' %}" method='POST'>
    {% csrf_token %}
    {% comment %} 제목 {% endcomment %}
    <label for="title">제목 : </label>
    <input type="text" id="title" name="title">
    <br>

    {% comment %} 내용 {% endcomment %}
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>


    {% comment %} 제출버튼 {% endcomment %}
    <input type="submit" value="게시글 작성">
  </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>